/* eslint-disable */
export type Schema = {
  'comments': {
    plain: {
      'id': number;
      'content': string;
      'UserId': number;
      'PostId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'User': Schema['users']['plain'] & Schema['users']['nested'];
      'Post': Schema['posts']['plain'] & Schema['posts']['nested'];
    };
    flat: {
      'User:id': number;
      'User:email': string;
      'User:nickname': string;
      'User:password': string;
      'User:createdAt': string;
      'User:updatedAt': string;
      'Post:id': number;
      'Post:content': string;
      'Post:UserId': number;
      'Post:RetweetId': number;
      'Post:createdAt': string;
      'Post:updatedAt': string;
      'Post:User:id': number;
      'Post:User:email': string;
      'Post:User:nickname': string;
      'Post:User:password': string;
      'Post:User:createdAt': string;
      'Post:User:updatedAt': string;
      'Post:Retweet:id': number;
      'Post:Retweet:content': string;
      'Post:Retweet:UserId': number;
      'Post:Retweet:RetweetId': number;
      'Post:Retweet:createdAt': string;
      'Post:Retweet:updatedAt': string;
      'Post:Retweet:User:id': number;
      'Post:Retweet:User:email': string;
      'Post:Retweet:User:nickname': string;
      'Post:Retweet:User:password': string;
      'Post:Retweet:User:createdAt': string;
      'Post:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:updatedAt': string;
    };
  };
  'follow': {
    plain: {
      'FollowingId': number;
      'FollowerId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'Following': Schema['users']['plain'] & Schema['users']['nested'];
      'Follower': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'Following:id': number;
      'Following:email': string;
      'Following:nickname': string;
      'Following:password': string;
      'Following:createdAt': string;
      'Following:updatedAt': string;
      'Follower:id': number;
      'Follower:email': string;
      'Follower:nickname': string;
      'Follower:password': string;
      'Follower:createdAt': string;
      'Follower:updatedAt': string;
    };
  };
  'hashtags': {
    plain: {
      'id': number;
      'name': string;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {};
    flat: {};
  };
  'images': {
    plain: {
      'id': number;
      'src': string;
      'PostId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'Post': Schema['posts']['plain'] & Schema['posts']['nested'];
    };
    flat: {
      'Post:id': number;
      'Post:content': string;
      'Post:UserId': number;
      'Post:RetweetId': number;
      'Post:createdAt': string;
      'Post:updatedAt': string;
      'Post:User:id': number;
      'Post:User:email': string;
      'Post:User:nickname': string;
      'Post:User:password': string;
      'Post:User:createdAt': string;
      'Post:User:updatedAt': string;
      'Post:Retweet:id': number;
      'Post:Retweet:content': string;
      'Post:Retweet:UserId': number;
      'Post:Retweet:RetweetId': number;
      'Post:Retweet:createdAt': string;
      'Post:Retweet:updatedAt': string;
      'Post:Retweet:User:id': number;
      'Post:Retweet:User:email': string;
      'Post:Retweet:User:nickname': string;
      'Post:Retweet:User:password': string;
      'Post:Retweet:User:createdAt': string;
      'Post:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:updatedAt': string;
    };
  };
  'like': {
    plain: {
      'PostId': number;
      'UserId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'Post': Schema['posts']['plain'] & Schema['posts']['nested'];
      'User': Schema['users']['plain'] & Schema['users']['nested'];
    };
    flat: {
      'Post:id': number;
      'Post:content': string;
      'Post:UserId': number;
      'Post:RetweetId': number;
      'Post:createdAt': string;
      'Post:updatedAt': string;
      'Post:User:id': number;
      'Post:User:email': string;
      'Post:User:nickname': string;
      'Post:User:password': string;
      'Post:User:createdAt': string;
      'Post:User:updatedAt': string;
      'Post:Retweet:id': number;
      'Post:Retweet:content': string;
      'Post:Retweet:UserId': number;
      'Post:Retweet:RetweetId': number;
      'Post:Retweet:createdAt': string;
      'Post:Retweet:updatedAt': string;
      'Post:Retweet:User:id': number;
      'Post:Retweet:User:email': string;
      'Post:Retweet:User:nickname': string;
      'Post:Retweet:User:password': string;
      'Post:Retweet:User:createdAt': string;
      'Post:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:updatedAt': string;
      'User:id': number;
      'User:email': string;
      'User:nickname': string;
      'User:password': string;
      'User:createdAt': string;
      'User:updatedAt': string;
    };
  };
  'posthashtag': {
    plain: {
      'HashtagId': number;
      'PostId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'Hashtag': Schema['hashtags']['plain'] & Schema['hashtags']['nested'];
      'Post': Schema['posts']['plain'] & Schema['posts']['nested'];
    };
    flat: {
      'Hashtag:id': number;
      'Hashtag:name': string;
      'Hashtag:createdAt': string;
      'Hashtag:updatedAt': string;
      'Post:id': number;
      'Post:content': string;
      'Post:UserId': number;
      'Post:RetweetId': number;
      'Post:createdAt': string;
      'Post:updatedAt': string;
      'Post:User:id': number;
      'Post:User:email': string;
      'Post:User:nickname': string;
      'Post:User:password': string;
      'Post:User:createdAt': string;
      'Post:User:updatedAt': string;
      'Post:Retweet:id': number;
      'Post:Retweet:content': string;
      'Post:Retweet:UserId': number;
      'Post:Retweet:RetweetId': number;
      'Post:Retweet:createdAt': string;
      'Post:Retweet:updatedAt': string;
      'Post:Retweet:User:id': number;
      'Post:Retweet:User:email': string;
      'Post:Retweet:User:nickname': string;
      'Post:Retweet:User:password': string;
      'Post:Retweet:User:createdAt': string;
      'Post:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:User:id': number;
      'Post:Retweet:Retweet:Retweet:User:email': string;
      'Post:Retweet:Retweet:Retweet:User:nickname': string;
      'Post:Retweet:Retweet:Retweet:User:password': string;
      'Post:Retweet:Retweet:Retweet:User:createdAt': string;
      'Post:Retweet:Retweet:Retweet:User:updatedAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:id': number;
      'Post:Retweet:Retweet:Retweet:Retweet:content': string;
      'Post:Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Post:Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Post:Retweet:Retweet:Retweet:Retweet:updatedAt': string;
    };
  };
  'posts': {
    plain: {
      'id': number;
      'content': string;
      'UserId': number;
      'RetweetId': number;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {
      'User': Schema['users']['plain'] & Schema['users']['nested'];
      'Retweet': Schema['posts']['plain'] & Schema['posts']['nested'];
    };
    flat: {
      'User:id': number;
      'User:email': string;
      'User:nickname': string;
      'User:password': string;
      'User:createdAt': string;
      'User:updatedAt': string;
      'Retweet:id': number;
      'Retweet:content': string;
      'Retweet:UserId': number;
      'Retweet:RetweetId': number;
      'Retweet:createdAt': string;
      'Retweet:updatedAt': string;
      'Retweet:User:id': number;
      'Retweet:User:email': string;
      'Retweet:User:nickname': string;
      'Retweet:User:password': string;
      'Retweet:User:createdAt': string;
      'Retweet:User:updatedAt': string;
      'Retweet:Retweet:id': number;
      'Retweet:Retweet:content': string;
      'Retweet:Retweet:UserId': number;
      'Retweet:Retweet:RetweetId': number;
      'Retweet:Retweet:createdAt': string;
      'Retweet:Retweet:updatedAt': string;
      'Retweet:Retweet:User:id': number;
      'Retweet:Retweet:User:email': string;
      'Retweet:Retweet:User:nickname': string;
      'Retweet:Retweet:User:password': string;
      'Retweet:Retweet:User:createdAt': string;
      'Retweet:Retweet:User:updatedAt': string;
      'Retweet:Retweet:Retweet:id': number;
      'Retweet:Retweet:Retweet:content': string;
      'Retweet:Retweet:Retweet:UserId': number;
      'Retweet:Retweet:Retweet:RetweetId': number;
      'Retweet:Retweet:Retweet:createdAt': string;
      'Retweet:Retweet:Retweet:updatedAt': string;
      'Retweet:Retweet:Retweet:User:id': number;
      'Retweet:Retweet:Retweet:User:email': string;
      'Retweet:Retweet:Retweet:User:nickname': string;
      'Retweet:Retweet:Retweet:User:password': string;
      'Retweet:Retweet:Retweet:User:createdAt': string;
      'Retweet:Retweet:Retweet:User:updatedAt': string;
      'Retweet:Retweet:Retweet:Retweet:id': number;
      'Retweet:Retweet:Retweet:Retweet:content': string;
      'Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Retweet:Retweet:Retweet:Retweet:updatedAt': string;
      'Retweet:Retweet:Retweet:Retweet:User:id': number;
      'Retweet:Retweet:Retweet:Retweet:User:email': string;
      'Retweet:Retweet:Retweet:Retweet:User:nickname': string;
      'Retweet:Retweet:Retweet:Retweet:User:password': string;
      'Retweet:Retweet:Retweet:Retweet:User:createdAt': string;
      'Retweet:Retweet:Retweet:Retweet:User:updatedAt': string;
      'Retweet:Retweet:Retweet:Retweet:Retweet:id': number;
      'Retweet:Retweet:Retweet:Retweet:Retweet:content': string;
      'Retweet:Retweet:Retweet:Retweet:Retweet:UserId': number;
      'Retweet:Retweet:Retweet:Retweet:Retweet:RetweetId': number;
      'Retweet:Retweet:Retweet:Retweet:Retweet:createdAt': string;
      'Retweet:Retweet:Retweet:Retweet:Retweet:updatedAt': string;
    };
  };
  'users': {
    plain: {
      'id': number;
      'email': string;
      'nickname': string;
      'password': string;
      'createdAt': string;
      'updatedAt': string;
    };
    nested: {};
    flat: {};
  };
};
